name: Builld WF
on:
  push:
    branches:
      - main
  
  pull_request:
    branches: 
      - "main"
  workflow_dispatch:

  schedule:
    - cron: "0 2 * * 1-5" 
  
permissions:
  contents: read

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Maven Build
        run:  mvn install
      - name: Uploda Build Artifact (WAR)
        uses: actions/upload-artifact@v4
        with:
          name: vprofile-app
          path: target/*.war

      - name: Notify if Build Fails
        if: failure()
        run: echo "Build job failed! Please check logs."

        
  Testing:
    runs-on: ubuntu-latest
    needs:  Build
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run tests on main branch
        run:  mvn test
      - name: Maven Build
        run:  mvn checkstyle:checkstyle